routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ConnexionController;
use App\Http\Controllers\Admin\ArticlesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('posts', PostController::class);

Route::resource('users', UserController::class);

//Route::resource('connexions', ConnexionController::class);

// Route::resource('connections', App\Http\Controllers\API\ConnectionAPIController::class);
// Route::resource('voitures', App\Http\Controllers\VoitureController::class);
// Route::resource('connections', App\Http\Controllers\ConnectionController::class);
// Route::resource('fiches', App\Http\Controllers\FicheController::class);
// Route::resource('personnes', App\Http\Controllers\personneController::class);
// Route::resource('portfolios', App\Http\Controllers\portfolioController::class);
// Route::resource('c-m-k-s', App\Http\Controllers\CMKController::class);
Route::resource('connexions', App\Http\Controllers\ConnexionController::class);

resources/views/layouts/menu.blade.php
<li class="nav-item">
    <a href="{{ route('connections.index') }}" class="nav-link {{ Request::is('connections*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-home"></i>
        <p>Connections</p>
    </a>
</li>

<li class="nav-item">
    <a href="{{ route('connections.index') }}" class="nav-link {{ Request::is('connections*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-home"></i>
        <p>Connections</p>
    </a>
</li>

<li class="nav-item">
    <a href="{{ route('voitures.index') }}" class="nav-link {{ Request::is('voitures*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-home"></i>
        <p>Voitures</p>
    </a>
</li>

<li class="nav-item">
    <a href="{{ route('fiches.index') }}" class="nav-link {{ Request::is('fiches*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-home"></i>
        <p>Fiches</p>
    </a>
</li>

<li class="nav-item">
    <a href="{{ route('personnes.index') }}" class="nav-link {{ Request::is('personnes*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-home"></i>
        <p>Personnes</p>
    </a>
</li>

<li class="nav-item">
    <a href="{{ route('portfolios.index') }}" class="nav-link {{ Request::is('portfolios*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-home"></i>
        <p>Portfolios</p>
    </a>
</li>

<li class="nav-item">
    <a href="{{ route('cMKS.index') }}" class="nav-link {{ Request::is('cMKS*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-home"></i>
        <p>C M K S</p>
    </a>
</li>

<li class="nav-item">
    <a href="{{ route('connexions.index') }}" class="nav-link {{ Request::is('connexions*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-home"></i>
        <p>Connexions</p>
    </a>
</li>